### ISSUE TITLE
ui problem maybe?

### ISSUE THREAD

**Issue by p4ttch** [dave-santiano/coding-apm-tracker#1]
wasnt able to find where the apm number was being outputted.

i installed the pluggin. restarted vs code.. started typing like a crazy person and couldnt see where the apm unit was being printed. was it too a file or does it display somewhere on screen?

**Comment by dave-santiano** [comment]
It displays on the UI and it should be on the bottom left! You also may not have activated it using the command palette, which you can access with "ctrl+shift+p" and then type APM to find "Track your apm!" as one of the commands

**Comment by p4ttch** [comment]
woops thanks! Yeah that worked, i havn't used a plugin where i have to activate it like that before.
